version: '3.9'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_DB_PROTOCOL=${MONGO_DB_PROTOCOL}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_DNS=${MONGO_DB_DNS}
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: banpay_web
    command: /start-web
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
  
volumes:
  mongodb_data: